### ISSUE TITLE
TypeError & AttributeError

### ISSUE THREAD

**Issue by stefan-it** [NAACL2018Anonymous/submission#1]
Hi,

thanks for releasing the code for your paper! I would really like to reproduce the results, but some error messages appear:

```bash
python run.py -epochs 10 -min 50 -setup zeroshot -criteria pred -datapath ./data/nocopy -fold 1
Initializing new seq 2 seq model
```

The output is:

```bash
Traceback (most recent call last):
  File "run.py", line 146, in <module>
    for d in iterator:
  File "/mnt/Zeroshot-QuestionGeneration-NAACL2018/data/data.py", line 372, in yield_datafeed
    {"epoch": epoch, "batch_id": bn, "ids": batchids, "placeholder_dict":[eval(i) for i in batch["placeholder_dict"].values]}  # meta info
TypeError: eval() arg 1 must be a string or code object
```

For the command:

```bash
python run.py -epochs 10 -min 50 -setup zeroshot -criteria pred -fold 1 -datapath ./data/nocopy/ -subtype -objtype -pred
```

The following error appears:

```bash
Traceback (most recent call last):
  File "run.py", line 136, in <module>
    model = TripleText2SeqModel(config)
  File "/mnt/Zeroshot-QuestionGeneration-NAACL2018/models/tripletext2seq.py", line 45, in __init__
    self.__create_encoder()
  File "/mnt/Zeroshot-QuestionGeneration-NAACL2018/models/tripletext2seq.py", line 264, in __create_encoder
    self.__create_seq_encoder()
  File "/mnt/Zeroshot-QuestionGeneration-NAACL2018/models/tripletext2seq.py", line 189, in __create_seq_encoder
    self.config.INPUT_SEQ_EMBEDDING_SIZE],
AttributeError: Config instance has no attribute 'INPUT_SEQ_EMBEDDING_SIZE'
```

I'm using TensorFlow in version *1.5* and a GPU.

Thanks many in advance + cheers,

Stefan

**Comment by hadyelsahar** [comment]
Hello Stefan, I am looking into this atm.

**Comment by hadyelsahar** [comment]
Sorry The problem that the current version of the training data wasn't up to date in the nocopy folder.
 The `.ids`files were missing the column which to replace back placeholders with their surface forms.
I uploaded the new version and tested it. So it is working at the moment. 
Thanks for your feedback! Feel free to open another issue if you are facing any problem running the code. 

![image](https://user-images.githubusercontent.com/1453243/38622375-5912dc2e-3da3-11e8-8449-63d22d6ff076.png)
